### ISSUE TITLE
Most recent winning game not listed on score page

### ISSUE THREAD

**Issue by d-s-s** [crawl/scoring#5]
**Describe the bug**
Score sheet and morque for most recent winning game saved on server but not present on score page

**To Reproduce**
Go to this link for the morque in question: https://cbro.berotato.org/morgue/freelancePsychic/morgue-freelancePsychic-20210729-224748.txt

Go to this link for the score page: http://crawl.akrasiac.org/scoring/players/freelancepsychic.html

**Expected behavior**
The KoDe game I just played should be listed under the DjAM game I won previously. However, as of this writing it has not posted even though it has been several hours.

**Comment by gammafunk** [comment]
Your game was played on the 0.27 release branch, and we usually don't update CAO scoring with the logfiles for the latest release until after the [tournament](https://crawl.develz.org/tournament/0.27/) is over. Your currently untracked games aren't lost, and will show up correctly on your player page after we update CAO scoring for 0.27.

Once the tournament starts (a couple hours from the time of this comment), you can also track your games played after that time [here](https://crawl.develz.org/tournament/0.27/players/freelancepsychic.html) (this page is not yet created).

**Comment by rawlins** [comment]
Small amendment: I will update the sources so that 0.27 games are tracked and pre-t games show up, but we usually do shut down scoring because of play load on cao so it may not reliably update during the tournament.
